### ISSUE TITLE
How to use BMInf to inference 100000.tar 11B model?

### ISSUE THREAD

**Issue by linjianz** [TsinghuaAI/CPM-2#20]
I install bminf from docker just like:

```bash
docker run -it --gpus 1 -v ${100000_MODEL_FILE_PATH}:/root/.cache/bigmodels --rm openbmb/bminf python3 examples/fill_blank.py
```

Where 100000_MODEL_FILE_PATH containers 4 .pt files in my localhost. However, I got the following error

```
Loading model
Failed to connect to the source server
Traceback (most recent call last):
  File "examples/fill_blank.py", line 29, in <module>
    main()
  File "examples/fill_blank.py", line 24, in main
    cpm2 = bminf.models.CPM2()
  File "/usr/local/lib/python3.6/dist-packages/bminf/models/cpm2.py", line 60, in __init__
    super().__init__(config)
  File "/usr/local/lib/python3.6/dist-packages/bminf/arch/t5/model.py", line 72, in __init__
    model_path = data.ensure_file(config.MODEL_NAME, "checkpoint.pt")
  File "/usr/local/lib/python3.6/dist-packages/bminf/data/__init__.py", line 49, in ensure_file
    raise ConnectionError("Failed to connect to the source server")
ConnectionError: Failed to connect to the source server
```

I also tried to convert the 4 .pt files into one .pt file, however, the same error occurred. How to solve the server connect problem?

**Comment by zzy14** [comment]
Hi! BMInf does not support the checkpoints with Torch format. If you want to use BMInf, you need to convert Torch checkpoints to BMinf checkpoints. For more details, you can refer to the BMInf repo.
